// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: sender.proto

package sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*Message_Login_
	//	*Message_CreatePassword_
	//	*Message_ResetPassword_
	//	*Message_TalkRecordingReady_
	Message isMessage_Message `protobuf_oneof:"message"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetMessage() isMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Message) GetLogin() *Message_Login {
	if x, ok := x.GetMessage().(*Message_Login_); ok {
		return x.Login
	}
	return nil
}

func (x *Message) GetCreatePassword() *Message_CreatePassword {
	if x, ok := x.GetMessage().(*Message_CreatePassword_); ok {
		return x.CreatePassword
	}
	return nil
}

func (x *Message) GetResetPassword() *Message_ResetPassword {
	if x, ok := x.GetMessage().(*Message_ResetPassword_); ok {
		return x.ResetPassword
	}
	return nil
}

func (x *Message) GetTalkRecordingReady() *Message_TalkRecordingReady {
	if x, ok := x.GetMessage().(*Message_TalkRecordingReady_); ok {
		return x.TalkRecordingReady
	}
	return nil
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_Login_ struct {
	Login *Message_Login `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type Message_CreatePassword_ struct {
	CreatePassword *Message_CreatePassword `protobuf:"bytes,2,opt,name=create_password,json=createPassword,proto3,oneof"`
}

type Message_ResetPassword_ struct {
	ResetPassword *Message_ResetPassword `protobuf:"bytes,3,opt,name=reset_password,json=resetPassword,proto3,oneof"`
}

type Message_TalkRecordingReady_ struct {
	TalkRecordingReady *Message_TalkRecordingReady `protobuf:"bytes,4,opt,name=talk_recording_ready,json=talkRecordingReady,proto3,oneof"`
}

func (*Message_Login_) isMessage_Message() {}

func (*Message_CreatePassword_) isMessage_Message() {}

func (*Message_ResetPassword_) isMessage_Message() {}

func (*Message_TalkRecordingReady_) isMessage_Message() {}

type Delivery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Delivery:
	//	*Delivery_Auto_
	//	*Delivery_Email_
	Delivery isDelivery_Delivery `protobuf_oneof:"delivery"`
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{1}
}

func (m *Delivery) GetDelivery() isDelivery_Delivery {
	if m != nil {
		return m.Delivery
	}
	return nil
}

func (x *Delivery) GetAuto() *Delivery_Auto {
	if x, ok := x.GetDelivery().(*Delivery_Auto_); ok {
		return x.Auto
	}
	return nil
}

func (x *Delivery) GetEmail() *Delivery_Email {
	if x, ok := x.GetDelivery().(*Delivery_Email_); ok {
		return x.Email
	}
	return nil
}

type isDelivery_Delivery interface {
	isDelivery_Delivery()
}

type Delivery_Auto_ struct {
	Auto *Delivery_Auto `protobuf:"bytes,1,opt,name=auto,proto3,oneof"`
}

type Delivery_Email_ struct {
	Email *Delivery_Email `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*Delivery_Auto_) isDelivery_Delivery() {}

func (*Delivery_Email_) isDelivery_Delivery() {}

type Send struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message  *Message  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Delivery *Delivery `protobuf:"bytes,2,opt,name=delivery,proto3" json:"delivery,omitempty"`
}

func (x *Send) Reset() {
	*x = Send{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Send) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Send) ProtoMessage() {}

func (x *Send) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Send.ProtoReflect.Descriptor instead.
func (*Send) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{2}
}

func (x *Send) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Send) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type Message_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretUrl string `protobuf:"bytes,1,opt,name=secret_url,json=secretUrl,proto3" json:"secret_url,omitempty"`
}

func (x *Message_Login) Reset() {
	*x = Message_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Login) ProtoMessage() {}

func (x *Message_Login) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Login.ProtoReflect.Descriptor instead.
func (*Message_Login) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Login) GetSecretUrl() string {
	if x != nil {
		return x.SecretUrl
	}
	return ""
}

type Message_CreatePassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretUrl string `protobuf:"bytes,1,opt,name=secret_url,json=secretUrl,proto3" json:"secret_url,omitempty"`
}

func (x *Message_CreatePassword) Reset() {
	*x = Message_CreatePassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_CreatePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_CreatePassword) ProtoMessage() {}

func (x *Message_CreatePassword) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_CreatePassword.ProtoReflect.Descriptor instead.
func (*Message_CreatePassword) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_CreatePassword) GetSecretUrl() string {
	if x != nil {
		return x.SecretUrl
	}
	return ""
}

type Message_ResetPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretUrl string `protobuf:"bytes,1,opt,name=secret_url,json=secretUrl,proto3" json:"secret_url,omitempty"`
}

func (x *Message_ResetPassword) Reset() {
	*x = Message_ResetPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_ResetPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_ResetPassword) ProtoMessage() {}

func (x *Message_ResetPassword) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_ResetPassword.ProtoReflect.Descriptor instead.
func (*Message_ResetPassword) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_ResetPassword) GetSecretUrl() string {
	if x != nil {
		return x.SecretUrl
	}
	return ""
}

type Message_TalkRecordingReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TalkUrl    string `protobuf:"bytes,1,opt,name=talk_url,json=talkUrl,proto3" json:"talk_url,omitempty"`
	ConfaUrl   string `protobuf:"bytes,2,opt,name=confa_url,json=confaUrl,proto3" json:"confa_url,omitempty"`
	ConfaTitle string `protobuf:"bytes,3,opt,name=confa_title,json=confaTitle,proto3" json:"confa_title,omitempty"`
	TalkTitle  string `protobuf:"bytes,4,opt,name=talk_title,json=talkTitle,proto3" json:"talk_title,omitempty"`
}

func (x *Message_TalkRecordingReady) Reset() {
	*x = Message_TalkRecordingReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_TalkRecordingReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_TalkRecordingReady) ProtoMessage() {}

func (x *Message_TalkRecordingReady) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_TalkRecordingReady.ProtoReflect.Descriptor instead.
func (*Message_TalkRecordingReady) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Message_TalkRecordingReady) GetTalkUrl() string {
	if x != nil {
		return x.TalkUrl
	}
	return ""
}

func (x *Message_TalkRecordingReady) GetConfaUrl() string {
	if x != nil {
		return x.ConfaUrl
	}
	return ""
}

func (x *Message_TalkRecordingReady) GetConfaTitle() string {
	if x != nil {
		return x.ConfaTitle
	}
	return ""
}

func (x *Message_TalkRecordingReady) GetTalkTitle() string {
	if x != nil {
		return x.TalkTitle
	}
	return ""
}

type Delivery_Auto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId []byte `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *Delivery_Auto) Reset() {
	*x = Delivery_Auto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delivery_Auto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery_Auto) ProtoMessage() {}

func (x *Delivery_Auto) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery_Auto.ProtoReflect.Descriptor instead.
func (*Delivery_Auto) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Delivery_Auto) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

type Delivery_Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToAddress string `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
}

func (x *Delivery_Email) Reset() {
	*x = Delivery_Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delivery_Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery_Email) ProtoMessage() {}

func (x *Delivery_Email) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery_Email.ProtoReflect.Descriptor instead.
func (*Delivery_Email) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Delivery_Email) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

var File_sender_proto protoreflect.FileDescriptor

var file_sender_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa,
	0x04, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x42, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x3f, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x74, 0x5f,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x65, 0x74, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x4f, 0x0a, 0x14, 0x74, 0x61, 0x6c, 0x6b, 0x5f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x54, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x48, 0x00, 0x52, 0x12, 0x74, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x64, 0x79, 0x1a, 0x26, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x55, 0x72, 0x6c,
	0x1a, 0x2f, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x55, 0x72,
	0x6c, 0x1a, 0x2e, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x55, 0x72,
	0x6c, 0x1a, 0x8c, 0x01, 0x0a, 0x12, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x6c, 0x6b,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x6c, 0x6b,
	0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x61, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x61, 0x55, 0x72, 0x6c,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x61, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x61, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x6c, 0x6b, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x6c, 0x6b, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x08,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x61, 0x75, 0x74, 0x6f, 0x12, 0x27,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x1f, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x6f, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x26, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x42, 0x0a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x22, 0x51, 0x0a, 0x04,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sender_proto_rawDescOnce sync.Once
	file_sender_proto_rawDescData = file_sender_proto_rawDesc
)

func file_sender_proto_rawDescGZIP() []byte {
	file_sender_proto_rawDescOnce.Do(func() {
		file_sender_proto_rawDescData = protoimpl.X.CompressGZIP(file_sender_proto_rawDescData)
	})
	return file_sender_proto_rawDescData
}

var file_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sender_proto_goTypes = []interface{}{
	(*Message)(nil),                    // 0: Message
	(*Delivery)(nil),                   // 1: Delivery
	(*Send)(nil),                       // 2: Send
	(*Message_Login)(nil),              // 3: Message.Login
	(*Message_CreatePassword)(nil),     // 4: Message.CreatePassword
	(*Message_ResetPassword)(nil),      // 5: Message.ResetPassword
	(*Message_TalkRecordingReady)(nil), // 6: Message.TalkRecordingReady
	(*Delivery_Auto)(nil),              // 7: Delivery.Auto
	(*Delivery_Email)(nil),             // 8: Delivery.Email
}
var file_sender_proto_depIdxs = []int32{
	3, // 0: Message.login:type_name -> Message.Login
	4, // 1: Message.create_password:type_name -> Message.CreatePassword
	5, // 2: Message.reset_password:type_name -> Message.ResetPassword
	6, // 3: Message.talk_recording_ready:type_name -> Message.TalkRecordingReady
	7, // 4: Delivery.auto:type_name -> Delivery.Auto
	8, // 5: Delivery.email:type_name -> Delivery.Email
	0, // 6: Send.message:type_name -> Message
	1, // 7: Send.delivery:type_name -> Delivery
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_sender_proto_init() }
func file_sender_proto_init() {
	if File_sender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delivery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Send); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_CreatePassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_ResetPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_TalkRecordingReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delivery_Auto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delivery_Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sender_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_Login_)(nil),
		(*Message_CreatePassword_)(nil),
		(*Message_ResetPassword_)(nil),
		(*Message_TalkRecordingReady_)(nil),
	}
	file_sender_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Delivery_Auto_)(nil),
		(*Delivery_Email_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sender_proto_goTypes,
		DependencyIndexes: file_sender_proto_depIdxs,
		MessageInfos:      file_sender_proto_msgTypes,
	}.Build()
	File_sender_proto = out.File
	file_sender_proto_rawDesc = nil
	file_sender_proto_goTypes = nil
	file_sender_proto_depIdxs = nil
}
