// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: sender.proto

package sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*Message_LoginViaEmail_
	Message isMessage_Message `protobuf_oneof:"message"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetMessage() isMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Message) GetLoginViaEmail() *Message_LoginViaEmail {
	if x, ok := x.GetMessage().(*Message_LoginViaEmail_); ok {
		return x.LoginViaEmail
	}
	return nil
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_LoginViaEmail_ struct {
	LoginViaEmail *Message_LoginViaEmail `protobuf:"bytes,1,opt,name=login_via_email,json=loginViaEmail,proto3,oneof"`
}

func (*Message_LoginViaEmail_) isMessage_Message() {}

type Delivery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Delivery:
	//	*Delivery_Email_
	Delivery isDelivery_Delivery `protobuf_oneof:"delivery"`
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{1}
}

func (m *Delivery) GetDelivery() isDelivery_Delivery {
	if m != nil {
		return m.Delivery
	}
	return nil
}

func (x *Delivery) GetEmail() *Delivery_Email {
	if x, ok := x.GetDelivery().(*Delivery_Email_); ok {
		return x.Email
	}
	return nil
}

type isDelivery_Delivery interface {
	isDelivery_Delivery()
}

type Delivery_Email_ struct {
	Email *Delivery_Email `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

func (*Delivery_Email_) isDelivery_Delivery() {}

type Send struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message  *Message  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Delivery *Delivery `protobuf:"bytes,2,opt,name=delivery,proto3" json:"delivery,omitempty"`
}

func (x *Send) Reset() {
	*x = Send{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Send) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Send) ProtoMessage() {}

func (x *Send) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Send.ProtoReflect.Descriptor instead.
func (*Send) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{2}
}

func (x *Send) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Send) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type Message_LoginViaEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretLoginUrl string `protobuf:"bytes,1,opt,name=secret_login_url,json=secretLoginUrl,proto3" json:"secret_login_url,omitempty"`
}

func (x *Message_LoginViaEmail) Reset() {
	*x = Message_LoginViaEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_LoginViaEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_LoginViaEmail) ProtoMessage() {}

func (x *Message_LoginViaEmail) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_LoginViaEmail.ProtoReflect.Descriptor instead.
func (*Message_LoginViaEmail) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_LoginViaEmail) GetSecretLoginUrl() string {
	if x != nil {
		return x.SecretLoginUrl
	}
	return ""
}

type Delivery_Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToAddress string `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
}

func (x *Delivery_Email) Reset() {
	*x = Delivery_Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delivery_Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery_Email) ProtoMessage() {}

func (x *Delivery_Email) ProtoReflect() protoreflect.Message {
	mi := &file_sender_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery_Email.ProtoReflect.Descriptor instead.
func (*Delivery_Email) Descriptor() ([]byte, []int) {
	return file_sender_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Delivery_Email) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

var File_sender_proto protoreflect.FileDescriptor

var file_sender_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91,
	0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x5f, 0x76, 0x69, 0x61, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x56, 0x69, 0x61, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x48, 0x00, 0x52, 0x0d, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x56, 0x69, 0x61, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x39, 0x0a, 0x0d,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x56, 0x69, 0x61, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x28, 0x0a,
	0x10, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x55, 0x72, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x67, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x27,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x26, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42,
	0x0a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x22, 0x51, 0x0a, 0x04, 0x53,
	0x65, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sender_proto_rawDescOnce sync.Once
	file_sender_proto_rawDescData = file_sender_proto_rawDesc
)

func file_sender_proto_rawDescGZIP() []byte {
	file_sender_proto_rawDescOnce.Do(func() {
		file_sender_proto_rawDescData = protoimpl.X.CompressGZIP(file_sender_proto_rawDescData)
	})
	return file_sender_proto_rawDescData
}

var file_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sender_proto_goTypes = []interface{}{
	(*Message)(nil),               // 0: Message
	(*Delivery)(nil),              // 1: Delivery
	(*Send)(nil),                  // 2: Send
	(*Message_LoginViaEmail)(nil), // 3: Message.LoginViaEmail
	(*Delivery_Email)(nil),        // 4: Delivery.Email
}
var file_sender_proto_depIdxs = []int32{
	3, // 0: Message.login_via_email:type_name -> Message.LoginViaEmail
	4, // 1: Delivery.email:type_name -> Delivery.Email
	0, // 2: Send.message:type_name -> Message
	1, // 3: Send.delivery:type_name -> Delivery
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sender_proto_init() }
func file_sender_proto_init() {
	if File_sender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delivery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Send); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_LoginViaEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delivery_Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sender_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_LoginViaEmail_)(nil),
	}
	file_sender_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Delivery_Email_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sender_proto_goTypes,
		DependencyIndexes: file_sender_proto_depIdxs,
		MessageInfos:      file_sender_proto_msgTypes,
	}.Build()
	File_sender_proto = out.File
	file_sender_proto_rawDesc = nil
	file_sender_proto_goTypes = nil
	file_sender_proto_depIdxs = nil
}
