version: '3.7'
services:
  nginx:
    image: nginx:1.19.6
    depends_on: 
      - web
      - rtc
      - api
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.dev.conf:/etc/nginx/nginx.conf

  web:
    image: node:15.7.0
    working_dir: /app
    command: bash -c "npm install -g pnpm; pnpm run serve"
    volumes:
      - ./web:/app

  rtc:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: "go run ./cmd/rtc/."
    environment:
      - ADDRESS=:80
      - LOG_FORMAT=console
    volumes:
      - ./api:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: "go run ./cmd/api/."
    depends_on:
      - beanstalkd
      - postgres
    environment:
      - ADDRESS=:80
      - BASE_URL=http://localhost
      - LOG_FORMAT=console
      - SECRET_KEY=LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUI4Zm1WV2hNZEFvL1VrRE5ONFVHbzhQWXdLeHovbE43bmlsbVlhMktFa2JvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVHJNZDBCcjdHT3BFN1VTMWpKN0xiTDBMOHZJaTNOeFJ4blhoT3hEV2FBaGQ0TXhkRjE3ZgpBWTVPR2pKcFBkV0o4VERNUUg3RXM5OFNBQjlwVlJWWmhnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
      - PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVHJNZDBCcjdHT3BFN1VTMWpKN0xiTDBMOHZJaQozTnhSeG5YaE94RFdhQWhkNE14ZEYxN2ZBWTVPR2pKcFBkV0o4VERNUUg3RXM5OFNBQjlwVlJWWmhnPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
      - MIGRATIONS_DIR=internal/migrations
      - EMAIL_SERVER=stub
      - EMAIL_PORT=42
      - EMAIL_ADDRESS=noreply@confa.io
      - EMAIL_PASSWORD=stub
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=confa
      - POSTGRES_PASSWORD=confa
      - POSTGRES_DATABASE=confa
      - BEANSTALKD_POOL=beanstalkd:11300
    volumes:
      - ./api:/app

  beanstalkd:
    build:
      context: ./beanstalkd
      dockerfile: Dockerfile
    volumes:
      - ./.artifacts/beanstalkd:/var/lib/beanstalkd

  postgres:
    image: postgres:12.6-alpine
    environment:
      - POSTGRES_USER=confa
      - POSTGRES_PASSWORD=confa
      - POSTGRES_DB=confa
    volumes:
      - ./.artifacts/postrgresql/:/var/lib/postgresql/data/
