version: '3.9'
services:
  web:
    image: confa/web
    restart: always
    network_mode: host
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/

  rtc:
    image: confa/rtc
    restart: always
    network_mode: host
    environment:
      - ADDRESS=:8001
      - ICE_PORT_MIN=10000
      - ICE_PORT_MAX=10999
      - LOG_FORMAT=console

  api:
    image: confa/api
    restart: always
    depends_on:
      - beanstalkd
      - postgres
    network_mode: host
    environment:
      - ADDRESS=:8002
      - BASE_URL=https://confa.io
      - LOG_FORMAT=console
      - SECRET_KEY=$SECRET_KEY
      - PUBLIC_KEY=$PUBLIC_KEY
      - EMAIL_SERVER=$EMAIL_SERVER
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - BEANSTALKD_POOL=$BEANSTALKD_POOL

  beanstalkd:
    image: confa/beanstalkd
    restart: always
    network_mode: host
    volumes:
      - /var/lib/beanstalkd:/var/lib/beanstalkd

  postgres:
    image: postgres:12.6-alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    volumes:
      - /var/lib/postgresql/:/var/lib/postgresql/
