version: '3.9'
services:
  nginx:
    image: nginx:1.19.6
    depends_on: 
      - web
      - rtc
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.dev.conf:/etc/nginx/nginx.conf

  web:
    image: node:15.7.0
    working_dir: /app
    command: bash -c "npm install -g pnpm; pnpm run serve"
    volumes:
      - ./web:/app

  rtc:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: "go run ./cmd/rtc/."
    environment:
      - ADDRESS=:8001
      - LOG_FORMAT=console
    volumes:
      - ./api:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: "go run ./cmd/api/."
    environment:
      - ADDRESS=:8002
      - LOG_FORMAT=console
      - EMAIL_SERVER=$EMAIL_SERVER
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=confa
      - POSTGRES_PASSWORD=confa
      - POSTGRES_DATABASE=confa
    volumes:
      - ./api:/app

  beanstalkd:
    build:
      context: ./beanstalkd
      dockerfile: Dockerfile
    volumes:
      - ./.artifacts/beanstalkd:/var/lib/beanstalkd

  postres:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postres
      - POSTGRES_PASSWORD=postres
      - POSTGRES_DB=confa
    volumes:
      - ./db:/var/lib/postgresql/data/
