version: '3.9'
services:
  nginx:
    build:
      context: ./web
      dockerfile: Dockerfile.remote
    network_mode: "host"
    volumes:
      - ./nginx.remote.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt/

  sfu:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: "go run ./cmd/sfu/."
    network_mode: "host"
    environment:
      - ADDRESS=:8080
      - LOG_FORMAT=console
      - ICE_PORT_MIN=5000
      - ICE_PORT_MAX=5200
    volumes:
      - ./api:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: "go run ./cmd/api/."
    network_mode: "host"
    depends_on:
      - beanstalkd
      - mongo
    environment:
      - ADDRESS=:8081
      - RPC_ADDRESS=:8082
      - RTC_ADDRESS=http://localhost:8082
      - BASE_URL=https://confa.io
      - LOG_FORMAT=console
      - SECRET_KEY=LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUI4Zm1WV2hNZEFvL1VrRE5ONFVHbzhQWXdLeHovbE43bmlsbVlhMktFa2JvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVHJNZDBCcjdHT3BFN1VTMWpKN0xiTDBMOHZJaTNOeFJ4blhoT3hEV2FBaGQ0TXhkRjE3ZgpBWTVPR2pKcFBkV0o4VERNUUg3RXM5OFNBQjlwVlJWWmhnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
      - PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVHJNZDBCcjdHT3BFN1VTMWpKN0xiTDBMOHZJaQozTnhSeG5YaE94RFdhQWhkNE14ZEYxN2ZBWTVPR2pKcFBkV0o4VERNUUg3RXM5OFNBQjlwVlJWWmhnPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
      - MIGRATIONS_DIR=internal/migrations
      - EMAIL_SERVER=smtp.yandex.com
      - EMAIL_PORT=465
      - EMAIL_ADDRESS=noreply@confa.io
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - MONGO_HOSTS=localhost:27017
      - MONGO_IAM_USER=iam
      - MONGO_IAM_PASSWORD=iam
      - MONGO_IAM_DATABASE=iam
      - MONGO_RTC_USER=rtc
      - MONGO_RTC_PASSWORD=rtc
      - MONGO_RTC_DATABASE=rtc
      - MONGO_CONFA_USER=confa
      - MONGO_CONFA_PASSWORD=confa
      - MONGO_CONFA_DATABASE=confa
      - BEANSTALKD_POOL=localhost:11300
      - RTC_SFU_ADDRESS=localhost:8080
      - RTC_MEDIA_ADDRESS=localhost:8090
    volumes:
      - ./api:/app

  beanstalkd:
    build:
      context: ./beanstalkd
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./.artifacts/beanstalkd:/var/lib/beanstalkd

  mongo:
    image: mongo:4.4
    command: "mongod --dbpath /data/db --replSet rs --keyFile /etc/mongo/mongo-repl.key"
    network_mode: "host"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./.artifacts/mongo/:/data/db
    entrypoint:
      - bash
      - -c
      - |
        mkdir /etc/mongo
        openssl rand -base64 768 > /etc/mongo/mongo-repl.key
        chmod 400 /etc/mongo/mongo-repl.key
        chown 999:999 /etc/mongo/mongo-repl.key
        exec docker-entrypoint.sh $$@
