version: '3.9'
services:
  web:
    image: confa/web
    restart: always
    network_mode: host
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/

  rtc:
    image: confa/rtc
    restart: always
    network_mode: host
    environment:
      - ADDRESS=:8001
      - ICE_PORT_MIN=10000
      - ICE_PORT_MAX=10999
      - LOG_FORMAT=console

  api:
    image: confa/api
    restart: always
    network_mode: host
    environment:
      - ADDRESS=:8002
      - LOG_FORMAT=console
      - EMAIL_SERVER=$EMAIL_SERVER
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE

  beanstalkd:
    image: confa/beanstalkd
    restart: always
    network_mode: host
    volumes:
      - /var/lib/beanstalkd:/var/lib/beanstalkd
