// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: avp.proto

package avp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessTrack_Kind int32

const (
	ProcessTrack_VIDEO ProcessTrack_Kind = 0
	ProcessTrack_AUDIO ProcessTrack_Kind = 1
)

// Enum value maps for ProcessTrack_Kind.
var (
	ProcessTrack_Kind_name = map[int32]string{
		0: "VIDEO",
		1: "AUDIO",
	}
	ProcessTrack_Kind_value = map[string]int32{
		"VIDEO": 0,
		"AUDIO": 1,
	}
)

func (x ProcessTrack_Kind) Enum() *ProcessTrack_Kind {
	p := new(ProcessTrack_Kind)
	*p = x
	return p
}

func (x ProcessTrack_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessTrack_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_avp_proto_enumTypes[0].Descriptor()
}

func (ProcessTrack_Kind) Type() protoreflect.EnumType {
	return &file_avp_proto_enumTypes[0]
}

func (x ProcessTrack_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessTrack_Kind.Descriptor instead.
func (ProcessTrack_Kind) EnumDescriptor() ([]byte, []int) {
	return file_avp_proto_rawDescGZIP(), []int{0, 0}
}

type ProcessTrack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket          string            `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object          string            `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	RoomId          []byte            `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordId        []byte            `protobuf:"bytes,4,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Kind            ProcessTrack_Kind `protobuf:"varint,5,opt,name=kind,proto3,enum=ProcessTrack_Kind" json:"kind,omitempty"`
	DurationSeconds float32           `protobuf:"fixed32,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
}

func (x *ProcessTrack) Reset() {
	*x = ProcessTrack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTrack) ProtoMessage() {}

func (x *ProcessTrack) ProtoReflect() protoreflect.Message {
	mi := &file_avp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTrack.ProtoReflect.Descriptor instead.
func (*ProcessTrack) Descriptor() ([]byte, []int) {
	return file_avp_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessTrack) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ProcessTrack) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ProcessTrack) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *ProcessTrack) GetRecordId() []byte {
	if x != nil {
		return x.RecordId
	}
	return nil
}

func (x *ProcessTrack) GetKind() ProcessTrack_Kind {
	if x != nil {
		return x.Kind
	}
	return ProcessTrack_VIDEO
}

func (x *ProcessTrack) GetDurationSeconds() float32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

var File_avp_proto protoreflect.FileDescriptor

var file_avp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x76, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x01, 0x0a, 0x0c,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x2e,
	0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x1c, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x09, 0x0a,
	0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x55, 0x44, 0x49,
	0x4f, 0x10, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_avp_proto_rawDescOnce sync.Once
	file_avp_proto_rawDescData = file_avp_proto_rawDesc
)

func file_avp_proto_rawDescGZIP() []byte {
	file_avp_proto_rawDescOnce.Do(func() {
		file_avp_proto_rawDescData = protoimpl.X.CompressGZIP(file_avp_proto_rawDescData)
	})
	return file_avp_proto_rawDescData
}

var file_avp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_avp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_avp_proto_goTypes = []interface{}{
	(ProcessTrack_Kind)(0), // 0: ProcessTrack.Kind
	(*ProcessTrack)(nil),   // 1: ProcessTrack
}
var file_avp_proto_depIdxs = []int32{
	0, // 0: ProcessTrack.kind:type_name -> ProcessTrack.Kind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_avp_proto_init() }
func file_avp_proto_init() {
	if File_avp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_avp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessTrack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_avp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_avp_proto_goTypes,
		DependencyIndexes: file_avp_proto_depIdxs,
		EnumInfos:         file_avp_proto_enumTypes,
		MessageInfos:      file_avp_proto_msgTypes,
	}.Build()
	File_avp_proto = out.File
	file_avp_proto_rawDesc = nil
	file_avp_proto_goTypes = nil
	file_avp_proto_depIdxs = nil
}
