version: 2.1
jobs:
  deploy_web:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - web-v1-{{ checksum "web/pnpm-lock.yaml" }}
            - web-v1
      - run: ./deploy/web.sh
      - save_cache:
          key: web-v1-{{ checksum "web/pnpm-lock.yaml" }}
          paths:
            - web/node_modules
            - web/.pnpm-store
  deploy_rtc:
    machine: true
    steps:
        - checkout
        - run: ./deploy/rtc.sh
  deploy_api:
    machine: true
    steps:
      - checkout
      - run: ./deploy/api.sh
  deploy_beanstalkd:
    machine: true
    steps:
      - checkout
      - run: ./deploy/beanstalkd.sh
  deploy_postgres:
    machine: true
    steps:
      - checkout
      - run: ./deploy/postgres.sh

workflows:
  version: 2.1
  web:
    jobs:
      - approve:
          type: approval
      - deploy_web:
          requires:
            - approve
  rtc:
    jobs:
      - approve:
          type: approval
      - deploy_rtc:
          requires:
            - approve
  api:
    jobs:
      - approve:
          type: approval
      - deploy_api:
          requires:
            - approve

  beanstalkd:
    jobs:
      - approve:
          type: approval
      - deploy_beanstalkd:
          requires:
            - approve

  postgres:
    jobs:
      - approve:
          type: approval
      - deploy_postgres:
          requires:
            - approve
