version: 2.1
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: |
          docker run --rm --network host \
            -v `pwd`/service-go:/app \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /app golang:1.17.5 \
            go test ./... -race -timeout 5m
  
  build:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run: |
          cd ./service-go
          go build -o bin/ ./cmd/iam/...
          go build -o bin/ ./cmd/confa/...
          go build -o bin/ ./cmd/rtc/...
          go build -o bin/ ./cmd/gateway/...
          go build -o bin/ ./cmd/sfu/...
  
  lint:
    docker:
      - image: golangci/golangci-lint:v1.45-alpine
    steps:
      - checkout
      - run: |
          cd ./service-go
          golangci-lint run

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
      - lint
