version: 2.1
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: |
          docker run --rm --network host \
            -v `pwd`/api:/app \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /app golang:1.16.3 \
            go test ./... -race -timeout 2m

  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: |
          cd ./api
          go build -o bin/ ./cmd/api/...
          go build -o bin/ ./cmd/media/...
          go build -o bin/ ./cmd/sfu/...
          go build -o bin/ ./cmd/turn/...

  lint:
    docker:
      - image: golangci/golangci-lint:v1.39-alpine
    steps:
      - checkout
      - run: |
          cd ./api
          golangci-lint run
