version: 2.1
jobs:
  deploy_web:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - web-v1-{{ checksum "web/pnpm-lock.yaml" }}
            - web-v1
      - run: ./deploy/web.sh
      - save_cache:
          key: web-v1-{{ checksum "web/pnpm-lock.yaml" }}
          paths:
            - web/node_modules
            - web/.pnpm-store
  deploy_rtc:
    machine: true
    steps:
        - checkout
        - run: ./deploy/rtc.sh
  deploy_api:
    machine: true
    steps:
      - checkout
      - run: ./deploy/api.sh
  deploy_beanstalkd:
    machine: true
    steps:
      - checkout
      - run: ./deploy/beanstalkd.sh
  deploy_postgres:
    machine: true
    steps:
      - checkout
      - run: ./deploy/postgres.sh

  migrate_user:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: |
          go get github.com/jackc/tern@v1.12.4
          echo '104.248.200.208 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLrTfZ3vhTWINNVt89U/2+b2JdtadRFOOPxiOrXOLGgbJbxIvmcPr3JTCemokSlD0ClDn+Qym6DS/0/+LeV6o7Q=' >> ~/.ssh/known_hosts
          tern migrate -m api/internal/user/migrations -c api/internal/user/migrations/tern.conf -d -+1

  migrate_confa:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: |
          go get github.com/jackc/tern@v1.12.4
          echo '104.248.200.208 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLrTfZ3vhTWINNVt89U/2+b2JdtadRFOOPxiOrXOLGgbJbxIvmcPr3JTCemokSlD0ClDn+Qym6DS/0/+LeV6o7Q=' >> ~/.ssh/known_hosts
          tern migrate -m api/internal/confa/migrations -c api/internal/confa/migrations/tern.conf -d -+1

workflows:
  version: 2.1
  web:
    jobs:
      - approve:
          type: approval
          filters:
            branches:
              only: "master"
      - deploy_web:
          requires:
            - approve
  rtc:
    jobs:
      - approve:
          type: approval
          filters:
            branches:
              only: "master"
      - deploy_rtc:
          requires:
            - approve
  api:
    jobs:
      - approve:
          type: approval
          filters:
            branches:
              only: "master"
      - deploy_api:
          requires:
            - approve

  beanstalkd:
    jobs:
      - approve:
          type: approval
          filters:
            branches:
              only: "master"
      - deploy_beanstalkd:
          requires:
            - approve

  postgres:
    jobs:
      - approve:
          type: approval
          filters:
            branches:
              only: "master"
      - deploy_postgres:
          requires:
            - approve

  migrate_user:
    jobs:
      - approve:
          type: approval
          filters:
            branches:
              only: "master"
      - migrate_user:
          requires:
            - approve

  migrate_confa:
    jobs:
      - approve:
          type: approval
          filters:
            branches:
              only: "master"
      - migrate_confa:
          requires:
            - approve
