version: '3.9'
services:
  web:
    image: confa/web
    restart: always
    network_mode: host
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/

  api:
    image: confa/api
    restart: always
    depends_on:
      - beanstalkd
      - postgres
    network_mode: host
    environment:
      - ADDRESS=:8001
      - BASE_URL=https://confa.io
      - LOG_FORMAT=console
      - SECRET_KEY=$SECRET_KEY
      - PUBLIC_KEY=$PUBLIC_KEY
      - MIGRATIONS_DIR=migrations
      - EMAIL_SERVER=$EMAIL_SERVER
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - BEANSTALKD_POOL=$BEANSTALKD_POOL
      - RTC_SFU_ADDRESS=localhost:8083
      - RTC_MEDIA_ADDRESS=localhost:8082

  media:
    image: confa/media
    restart: always
    environment:
      - HTTP_ADDRESS=:8002
      - RPC_ADDRESS=:8082
      - SFU_ADDRESS=:8083
      - MEDIA_DIR=/var/lib/media
      - BEANSTALKD_POOL=$BEANSTALKD_POOL
      - LOG_FORMAT=console
    volumes:
      - ./api:/app
      - ./.artifacts/media:/var/lib/media

  sfu:
    image: confa/sfu
    restart: always
    network_mode: host
    environment:
      - ADDRESS=:8083
      - ICE_PORT_MIN=10000
      - ICE_PORT_MAX=10999
      - LOG_FORMAT=console

  beanstalkd:
    image: confa/beanstalkd
    restart: always
    network_mode: host
    volumes:
      - /var/lib/beanstalkd:/var/lib/beanstalkd

  postgres:
    image: postgres:12.6-alpine
    restart: always
    network_mode: host
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    volumes:
      - /var/lib/postgresql/:/var/lib/postgresql/
