version: '3.9'
services:
  sfu:
    build:
      context: ../service-go
      dockerfile: ./cmd/sfu/Dockerfile
    network_mode: "host"
    environment:
      - ADDRESS=:8080
      - LOG_FORMAT=console
      - ICE_PORT_MIN=50000
      - ICE_PORT_MAX=60000

  turn:
    build:
      context: ../service-go
      dockerfile: ./cmd/turn/Dockerfile
    network_mode: "host"
    environment:
      - ADDRESS=:3478
      - LOG_FORMAT=console
      - REALM=confa.io
      - USERNAME=confa
      - CREDENTIAL=confa
      - PUBLIC_IP=31.184.253.195
      - PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVHJNZDBCcjdHT3BFN1VTMWpKN0xiTDBMOHZJaQozTnhSeG5YaE94RFdhQWhkNE14ZEYxN2ZBWTVPR2pKcFBkV0o4VERNUUg3RXM5OFNBQjlwVlJWWmhnPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
