// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package web

type Clap struct {
	Owner   string `json:"owner"`
	Speaker string `json:"speaker"`
	Confa   string `json:"confa"`
	Talk    string `json:"talk"`
	Claps   int    `json:"claps"`
}

type ClapInput struct {
	Owner   *string `json:"owner"`
	Speaker *string `json:"speaker"`
	Confa   *string `json:"confa"`
	Talk    *string `json:"talk"`
}

type Confa struct {
	ID     string `json:"id"`
	Owner  string `json:"owner"`
	Handle string `json:"handle"`
}

type ConfaInput struct {
	ID     *string `json:"id"`
	Owner  *string `json:"owner"`
	Handle *string `json:"handle"`
}

type Confas struct {
	Items    []*Confa `json:"items"`
	Limit    int      `json:"limit"`
	NextFrom string   `json:"nextFrom"`
}

type Talk struct {
	ID      string `json:"id"`
	Owner   string `json:"owner"`
	Speaker string `json:"speaker"`
	Confa   string `json:"confa"`
	Handle  string `json:"handle"`
}

type TalkInput struct {
	ID      *string `json:"id"`
	Owner   *string `json:"owner"`
	Speaker *string `json:"speaker"`
	Confa   *string `json:"confa"`
	Handle  *string `json:"handle"`
}

type Talks struct {
	Items    []*Talk `json:"items"`
	Limit    int     `json:"limit"`
	NextFrom string  `json:"nextFrom"`
}

type Token struct {
	Token     string `json:"token"`
	ExpiresIn int    `json:"expiresIn"`
}
