version: '3.9'
services:
  caddy:
    image: livekit/caddyl4
    command: run --config /etc/caddy.yaml --adapter yaml
    restart: on-failure
    network_mode: "host"
    volumes:
      - ./caddy.yaml:/etc/caddy.yaml
      - ./.artifacts/caddy:/data
  livekit:
    image: livekit/livekit-server:v1.4
    command: --config /etc/livekit/config.yml
    restart: on-failure
    network_mode: "host"
    volumes:
      - ./livekit.yml:/etc/livekit/config.yml
