# main TCP port for RoomService and RTC endpoint
# for production setups, this port should be placed behind a load balancer with TLS
port: 7880

# WebRTC configuration
rtc:
  # UDP ports to use for client traffic.
  # this port range should be open for inbound traffic on the firewall
  port_range_start: 5000
  port_range_end: 6000
  # when set, LiveKit enable WebRTC ICE over TCP when UDP isn't available
  # this port *cannot* be behind load balancer or TLS, and must be exposed on the node
  # WebRTC transports are encrypted and do not require additional encryption
  # only 80/443 on public IP are allowed if less than 1024
  tcp_port: 7881
  # when set, LiveKit will attempt to use a UDP mux so all UDP traffic goes through
  # a single port. This simplifies deployment, but mux will become an overhead for
  # highly trafficked deployments.
  # port_range_start & end must not be set for this config to take effect
  udp_port: 7882
  turn_servers:
    - host: localhost
      port: 3478
      # tls, tcp, or udp
      protocol: tcp
      username: "confa"
      credential: "confa"

# Signal Relay
# since v1.4.0, a more reliable, psrpc based signal relay is available
# this gives us the ability to reliably proxy messages between a signal server and RTC node
signal_relay:
  # disabled by default. will be enabled by default in future versions
  enabled: true

# API key / secret pairs.
# Keys are used for JWT authentication, server APIs would require a keypair in order to generate access tokens
# and make calls to the server
keys:
  devkey: 93d33a06-f209-4239-bd7f-d04d411ae7b2

# Logging config
logging:
  # log level, valid values: debug, info, warn, error
  level: error
  # log level for pion, default error
  pion_level: error
  # when set to true, emit json fields
  json: false
  # for production setups, enables sampling algorithm
  # https://github.com/uber-go/zap/blob/master/FAQ.md#why-sample-application-logs
  sample: false
