// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: confa.proto

package confa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        []byte                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GivenNameSet  bool                      `protobuf:"varint,2,opt,name=given_name_set,json=givenNameSet,proto3" json:"given_name_set,omitempty"`
	GivenName     string                    `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyNameSet bool                      `protobuf:"varint,4,opt,name=family_name_set,json=familyNameSet,proto3" json:"family_name_set,omitempty"`
	FamilyName    string                    `protobuf:"bytes,5,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Thumbnail     *UpdateProfile_FileSource `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Avatar        *UpdateProfile_FileSource `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// TODO: Remove this when migrated to event-based message queue and create a new event.
	SkipIfExists bool `protobuf:"varint,8,opt,name=skip_if_exists,json=skipIfExists,proto3" json:"skip_if_exists,omitempty"`
}

func (x *UpdateProfile) Reset() {
	*x = UpdateProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_confa_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfile) ProtoMessage() {}

func (x *UpdateProfile) ProtoReflect() protoreflect.Message {
	mi := &file_confa_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfile.ProtoReflect.Descriptor instead.
func (*UpdateProfile) Descriptor() ([]byte, []int) {
	return file_confa_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateProfile) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *UpdateProfile) GetGivenNameSet() bool {
	if x != nil {
		return x.GivenNameSet
	}
	return false
}

func (x *UpdateProfile) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *UpdateProfile) GetFamilyNameSet() bool {
	if x != nil {
		return x.FamilyNameSet
	}
	return false
}

func (x *UpdateProfile) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *UpdateProfile) GetThumbnail() *UpdateProfile_FileSource {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *UpdateProfile) GetAvatar() *UpdateProfile_FileSource {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *UpdateProfile) GetSkipIfExists() bool {
	if x != nil {
		return x.SkipIfExists
	}
	return false
}

type StartRecording struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TalkId []byte `protobuf:"bytes,1,opt,name=talk_id,json=talkId,proto3" json:"talk_id,omitempty"`
	RoomId []byte `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *StartRecording) Reset() {
	*x = StartRecording{}
	if protoimpl.UnsafeEnabled {
		mi := &file_confa_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRecording) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecording) ProtoMessage() {}

func (x *StartRecording) ProtoReflect() protoreflect.Message {
	mi := &file_confa_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecording.ProtoReflect.Descriptor instead.
func (*StartRecording) Descriptor() ([]byte, []int) {
	return file_confa_proto_rawDescGZIP(), []int{1}
}

func (x *StartRecording) GetTalkId() []byte {
	if x != nil {
		return x.TalkId
	}
	return nil
}

func (x *StartRecording) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

type StopRecording struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TalkId []byte `protobuf:"bytes,1,opt,name=talk_id,json=talkId,proto3" json:"talk_id,omitempty"`
	RoomId []byte `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *StopRecording) Reset() {
	*x = StopRecording{}
	if protoimpl.UnsafeEnabled {
		mi := &file_confa_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRecording) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecording) ProtoMessage() {}

func (x *StopRecording) ProtoReflect() protoreflect.Message {
	mi := &file_confa_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecording.ProtoReflect.Descriptor instead.
func (*StopRecording) Descriptor() ([]byte, []int) {
	return file_confa_proto_rawDescGZIP(), []int{2}
}

func (x *StopRecording) GetTalkId() []byte {
	if x != nil {
		return x.TalkId
	}
	return nil
}

func (x *StopRecording) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

type RecordingUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId      []byte                  `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordingId []byte                  `protobuf:"bytes,2,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	UpdatedAt   int64                   `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Update      *RecordingUpdate_Update `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *RecordingUpdate) Reset() {
	*x = RecordingUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_confa_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingUpdate) ProtoMessage() {}

func (x *RecordingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_confa_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingUpdate.ProtoReflect.Descriptor instead.
func (*RecordingUpdate) Descriptor() ([]byte, []int) {
	return file_confa_proto_rawDescGZIP(), []int{3}
}

func (x *RecordingUpdate) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *RecordingUpdate) GetRecordingId() []byte {
	if x != nil {
		return x.RecordingId
	}
	return nil
}

func (x *RecordingUpdate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RecordingUpdate) GetUpdate() *RecordingUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateProfile_FileSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Storage   *UpdateProfile_FileSource_Storage   `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	PublicUrl *UpdateProfile_FileSource_PublicURL `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
}

func (x *UpdateProfile_FileSource) Reset() {
	*x = UpdateProfile_FileSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_confa_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfile_FileSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfile_FileSource) ProtoMessage() {}

func (x *UpdateProfile_FileSource) ProtoReflect() protoreflect.Message {
	mi := &file_confa_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfile_FileSource.ProtoReflect.Descriptor instead.
func (*UpdateProfile_FileSource) Descriptor() ([]byte, []int) {
	return file_confa_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UpdateProfile_FileSource) GetStorage() *UpdateProfile_FileSource_Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *UpdateProfile_FileSource) GetPublicUrl() *UpdateProfile_FileSource_PublicURL {
	if x != nil {
		return x.PublicUrl
	}
	return nil
}

type UpdateProfile_FileSource_Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *UpdateProfile_FileSource_Storage) Reset() {
	*x = UpdateProfile_FileSource_Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_confa_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfile_FileSource_Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfile_FileSource_Storage) ProtoMessage() {}

func (x *UpdateProfile_FileSource_Storage) ProtoReflect() protoreflect.Message {
	mi := &file_confa_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfile_FileSource_Storage.ProtoReflect.Descriptor instead.
func (*UpdateProfile_FileSource_Storage) Descriptor() ([]byte, []int) {
	return file_confa_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *UpdateProfile_FileSource_Storage) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UpdateProfile_FileSource_Storage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UpdateProfile_FileSource_PublicURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *UpdateProfile_FileSource_PublicURL) Reset() {
	*x = UpdateProfile_FileSource_PublicURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_confa_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfile_FileSource_PublicURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfile_FileSource_PublicURL) ProtoMessage() {}

func (x *UpdateProfile_FileSource_PublicURL) ProtoReflect() protoreflect.Message {
	mi := &file_confa_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfile_FileSource_PublicURL.ProtoReflect.Descriptor instead.
func (*UpdateProfile_FileSource_PublicURL) Descriptor() ([]byte, []int) {
	return file_confa_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *UpdateProfile_FileSource_PublicURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RecordingUpdate_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Update:
	//	*RecordingUpdate_Update_ProcessingFinished
	Update isRecordingUpdate_Update_Update `protobuf_oneof:"update"`
}

func (x *RecordingUpdate_Update) Reset() {
	*x = RecordingUpdate_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_confa_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordingUpdate_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingUpdate_Update) ProtoMessage() {}

func (x *RecordingUpdate_Update) ProtoReflect() protoreflect.Message {
	mi := &file_confa_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingUpdate_Update.ProtoReflect.Descriptor instead.
func (*RecordingUpdate_Update) Descriptor() ([]byte, []int) {
	return file_confa_proto_rawDescGZIP(), []int{3, 0}
}

func (m *RecordingUpdate_Update) GetUpdate() isRecordingUpdate_Update_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *RecordingUpdate_Update) GetProcessingFinished() *RecordingUpdate_ProcessingFinished {
	if x, ok := x.GetUpdate().(*RecordingUpdate_Update_ProcessingFinished); ok {
		return x.ProcessingFinished
	}
	return nil
}

type isRecordingUpdate_Update_Update interface {
	isRecordingUpdate_Update_Update()
}

type RecordingUpdate_Update_ProcessingFinished struct {
	ProcessingFinished *RecordingUpdate_ProcessingFinished `protobuf:"bytes,1,opt,name=processing_finished,json=processingFinished,proto3,oneof"`
}

func (*RecordingUpdate_Update_ProcessingFinished) isRecordingUpdate_Update_Update() {}

type RecordingUpdate_ProcessingFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecordingUpdate_ProcessingFinished) Reset() {
	*x = RecordingUpdate_ProcessingFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_confa_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordingUpdate_ProcessingFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingUpdate_ProcessingFinished) ProtoMessage() {}

func (x *RecordingUpdate_ProcessingFinished) ProtoReflect() protoreflect.Message {
	mi := &file_confa_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingUpdate_ProcessingFinished.ProtoReflect.Descriptor instead.
func (*RecordingUpdate_ProcessingFinished) Descriptor() ([]byte, []int) {
	return file_confa_proto_rawDescGZIP(), []int{3, 1}
}

var File_confa_proto protoreflect.FileDescriptor

var file_confa_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x04,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x67, 0x69, 0x76, 0x65,
	0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x67, 0x69, 0x76, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x67, 0x69, 0x76, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x67, 0x69, 0x76, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12,
	0x31, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x69, 0x66, 0x5f, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73, 0x6b, 0x69, 0x70,
	0x49, 0x66, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x1a, 0xe3, 0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x12, 0x42, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x55, 0x52, 0x4c, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x1a, 0x35, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x1a,
	0x1d, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x55, 0x52, 0x4c, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x42,
	0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x6c, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x74, 0x61, 0x6c, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x22, 0x41, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x6c, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61, 0x6c, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x9f, 0x02, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x6a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x56, 0x0a, 0x13, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x1a, 0x14, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_confa_proto_rawDescOnce sync.Once
	file_confa_proto_rawDescData = file_confa_proto_rawDesc
)

func file_confa_proto_rawDescGZIP() []byte {
	file_confa_proto_rawDescOnce.Do(func() {
		file_confa_proto_rawDescData = protoimpl.X.CompressGZIP(file_confa_proto_rawDescData)
	})
	return file_confa_proto_rawDescData
}

var file_confa_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_confa_proto_goTypes = []interface{}{
	(*UpdateProfile)(nil),                      // 0: UpdateProfile
	(*StartRecording)(nil),                     // 1: StartRecording
	(*StopRecording)(nil),                      // 2: StopRecording
	(*RecordingUpdate)(nil),                    // 3: RecordingUpdate
	(*UpdateProfile_FileSource)(nil),           // 4: UpdateProfile.FileSource
	(*UpdateProfile_FileSource_Storage)(nil),   // 5: UpdateProfile.FileSource.Storage
	(*UpdateProfile_FileSource_PublicURL)(nil), // 6: UpdateProfile.FileSource.PublicURL
	(*RecordingUpdate_Update)(nil),             // 7: RecordingUpdate.Update
	(*RecordingUpdate_ProcessingFinished)(nil), // 8: RecordingUpdate.ProcessingFinished
}
var file_confa_proto_depIdxs = []int32{
	4, // 0: UpdateProfile.thumbnail:type_name -> UpdateProfile.FileSource
	4, // 1: UpdateProfile.avatar:type_name -> UpdateProfile.FileSource
	7, // 2: RecordingUpdate.update:type_name -> RecordingUpdate.Update
	5, // 3: UpdateProfile.FileSource.storage:type_name -> UpdateProfile.FileSource.Storage
	6, // 4: UpdateProfile.FileSource.public_url:type_name -> UpdateProfile.FileSource.PublicURL
	8, // 5: RecordingUpdate.Update.processing_finished:type_name -> RecordingUpdate.ProcessingFinished
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_confa_proto_init() }
func file_confa_proto_init() {
	if File_confa_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_confa_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_confa_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRecording); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_confa_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopRecording); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_confa_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordingUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_confa_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfile_FileSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_confa_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfile_FileSource_Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_confa_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfile_FileSource_PublicURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_confa_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordingUpdate_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_confa_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordingUpdate_ProcessingFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_confa_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*RecordingUpdate_Update_ProcessingFinished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_confa_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_confa_proto_goTypes,
		DependencyIndexes: file_confa_proto_depIdxs,
		MessageInfos:      file_confa_proto_msgTypes,
	}.Build()
	File_confa_proto = out.File
	file_confa_proto_rawDesc = nil
	file_confa_proto_goTypes = nil
	file_confa_proto_depIdxs = nil
}
