// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package avp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AVPClient is the client API for AVP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AVPClient interface {
	Signal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type aVPClient struct {
	cc grpc.ClientConnInterface
}

func NewAVPClient(cc grpc.ClientConnInterface) AVPClient {
	return &aVPClient{cc}
}

func (c *aVPClient) Signal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/AVP/Signal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AVPServer is the server API for AVP service.
// All implementations must embed UnimplementedAVPServer
// for forward compatibility
type AVPServer interface {
	Signal(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedAVPServer()
}

// UnimplementedAVPServer must be embedded to have forward compatible implementations.
type UnimplementedAVPServer struct {
}

func (UnimplementedAVPServer) Signal(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedAVPServer) mustEmbedUnimplementedAVPServer() {}

// UnsafeAVPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AVPServer will
// result in compilation errors.
type UnsafeAVPServer interface {
	mustEmbedUnimplementedAVPServer()
}

func RegisterAVPServer(s grpc.ServiceRegistrar, srv AVPServer) {
	s.RegisterService(&AVP_ServiceDesc, srv)
}

func _AVP_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AVPServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AVP/Signal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AVPServer).Signal(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AVP_ServiceDesc is the grpc.ServiceDesc for AVP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AVP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AVP",
	HandlerType: (*AVPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signal",
			Handler:    _AVP_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avp.proto",
}
