name: Beanstalk
on:
  push:
    branches: 
      - main
      - test
    paths:
      - beanstalk/**

jobs:
  build-and-push:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - uses: ./.github/actions/build-and-push
        with:
          user: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: beanstalk
          dir: ./beanstalk
