name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy all applications
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v3

      - working-directory: ./deploy/nomad
        run: |
          nomad job run beanstalk.nomad.hcl
          nomad job run mongodb.nomad.hcl
          nomad job run web.nomad.hcl
          nomad job run iam.nomad.hcl
          nomad job run traefik.nomad.hcl
