name: Deploy All
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy all services
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Deploy all services
        working-directory: ./deploy/nomad
        run: |
          nomad job run -detach beanstalk.nomad.hcl
          nomad job run -detach iam.nomad.hcl
          nomad job run -detach mongodb.nomad.hcl
          nomad job run -detach traefik.nomad.hcl
          nomad job run -detach web.nomad.hcl
