name: Deploy MongoDB
on:
  push:
    branches:
      - main
    paths:
      - deploy/mongodb.nomad.hcl

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        working-directory: ./deploy/nomad
        run: nomad job run mongodb.nomad.hcl
