name: Services
on:
  push:
    branches:
      - main
    paths:
      - services/**
  pull_request:
    branches:
      - main
    paths:
      - services/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.19"
          cache: false

      - name: Test
        working-directory: ./services
        run: go test ./... -timeout 5m

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.19"
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
          working-directory: ./services

  build-iam:
    name: Build iam
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: ./.github/actions/build-and-push
        with:
          user: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: iam
          context: ./services
          file: ./services/cmd/iam/Dockerfile

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.19"
          cache: false

      - name: Build
        working-directory: ./services
        run: |
          go build -o bin/ ./cmd/iam/...
          go build -o bin/ ./cmd/confa/...
          go build -o bin/ ./cmd/rtc/...
          go build -o bin/ ./cmd/gateway/...
          go build -o bin/ ./cmd/tracker/...
          go build -o bin/ ./cmd/avp/...
          go build -o bin/ ./cmd/sender/...
          go build -o bin/ ./cmd/sender-clients/...
