FROM node:14.16

RUN npm install -g pnpm apollo@2.33.9

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY index.html .eslintrc.js .prettierrc.js apollo.config.js vite.config.ts tsconfig.json ./
