FROM node:16.15

RUN npm install -g \
    pnpm@7.1.0 \
    apollo@2.33.9 \
    graphql@15.5.1 \
    quicktype@15.0.260

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install
ENV PATH /app/node_modules/.bin:$PATH
